repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
    name: Lint YAML
    stages: [push]
  - id: check-added-large-files
    stages: [commit]
- repo: https://gitlab.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    stages: [push]
- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    stages: [push]
    types: [python]
    entry: poetry run pytest
    language: system
    pass_filenames: false
    always_run: true