[tool.poetry]
name = "serenity.sdk.python"
version = "0.0.0"
authors = ["Cloudwall DevSecOps <support@cloudwall.capital>"]

description = "Python SDK for the Serenity digital asset risk API"
readme = "README.md"
license = "MIT"
packages = [
    { include = "serenity_sdk/**/*.py", from = "src/python" }
]

[tool.poetry.dependencies]
python = ">=3.7,<4"
azure-identity = "^1.10.0"
fire = "^0.4.0"

[project.urls]
"Homepage" = "https://github.com/cloudwall/serenity.sdk.python"
"Bug Tracker" = "https://github.com/cloudwall/serenity.sdk.python/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry_bumpversion.file."src/python/serenity_sdk/__init__.py"]
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'