name: Continuous Integration

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SRC_DIR: src/python
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry flake8 pytest radon
      - name: Install Runtime Dependencies
        run: |
          poetry install --no-root
          /home/runner/.cache/pypoetry/virtualenvs/serenity.sdk.python-KZYnopbe-py3.8/bin/pip list
      - name: Lint
        run: flake8 $SRC_DIR tests --count --show-source --statistics --radon-max-cc 5
      - name: Analyze Complexity
        run: radon cc $SRC_DIR
      - name: Test
        run: |
          pip list
          PYTHONPATH=$SRC_DIR poetry run pytest tests/
