name: Publish

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        tag_prefix: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        prerelease: true
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Build Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.2.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install Poetry Plugin
      run: poetry self add poetry-bumpversion
    - name: Build Package
      run: |
        # bumpversion plugin will ensure new version applied in all places
        poetry version ${{ steps.tag_version.outputs.new_tag }}
        python -m build
    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
