name: Publish

on: 
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version of the code to publish to PyPi'     
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install Poetry Plugin
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-bumpversion
    - name: Build and Publish
      run: |
        poetry version ${{ github.event.inputs.releaseVersion }}
        poetry build
        poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}        
