name: Publish

on: 
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version of the code to publish to PyPi'     
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Build Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.2.0rc2
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install Poetry Plugin
      run: poetry self add poetry-bumpversion
    - name: Build Package
      run: |
        poetry version ${{ github.event.inputs.releaseVersion }}
        python -m build
    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
